[http]
    [http.routers]

        [http.routers.api-router]
            rule = "Host(`dashboard.demo1.iotstack.co`)"
            entryPoints = ["web-secure"]
            middlewares = ["user-auth"]
            service = "api@internal"
            
            [http.routers.api-router.tls]
                certResolver = "myresolver"

        [http.routers.grafana-router]
            rule = "Host(`grafana.demo1.iotstack.co`)"
            entryPoints = ["web-secure"]
            service = "grafana"

            [http.routers.grafana-router.tls]
                certResolver = "myresolver"

        [http.routers.cedalo-router]
            rule = "Host(`mqttadmin.demo1.iotstack.co`)"
            entryPoints = ["web-secure"]
            middlewares = ["user-auth"]
            service = "cedalo"

            [http.routers.cedalo-router.tls]
                certResolver = "myresolver"
        
        [http.routers.influxdb-router]
            rule = "Host(`influxdb.demo1.iotstack.co`)"
            entryPoints = ["web-secure"]
            service = "influxdb"

            [http.routers.influxdb-router.tls]
                certResolver = "myresolver"
